in:
  type: file
  path_prefix: data.jsonl
  parser:
    type: none
    column_name: payload

filters:
  - type: speedometer
    log_interval_seconds: 1
  - type: expand_json
    json_column_name: payload
    cache_provider: noop
    root: "$."
    expanded_columns:
      - {name: "phone_numbers", type: string}
      - {name: "app_id", type: long}
      - {name: "point", type: double}
      - {name: "created_at", type: timestamp, format: "%Y-%m-%d"}
      - {name: "profile", type: json}

out:
  type: "null"

